# Generated by Django 2.2 on 2019-09-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
